#!/usr/bin/env node
import inquirer from 'inquirer';
import chalk from 'chalk';
import fs from 'fs';
import path from 'path';

const FINGERPRINT = {
  standard: 'TRESSLERS_MIP_STANDARD_V1',
  generator: 'MIP-Scaffold-Pro',
  authority: 'Tresslers Group Deep Research',
};

async function run() {
  console.log(chalk.cyan.bold('\n--- MIP-Scaffold-Pro: Sovereign AI Discovery Generator ---'));
  console.log(chalk.dim('Provided by Tresslers Group Deep Research Division\n'));

  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'entityName',
      message: 'Enter Entity/Company Name:',
      default: 'My Autonomous Venture',
    },
    {
      type: 'input',
      name: 'mission',
      message: 'Enter Mission Statement:',
      default: 'Driving innovation through agentic synergy.',
    },
    {
      type: 'input',
      name: 'domain',
      message: 'Enter Primary Domain (e.g., example.com):',
    },
    {
      type: 'input',
      name: 'masterWallet',
      message: 'Enter Master Wallet Address (for x402 settlement):',
      default: '0x0000000000000000000000000000000000000000',
    },
    {
      type: 'confirm',
      name: 'enforceX402',
      message: 'Enforce x402 Economic Handshake?',
      default: true,
    },
  ]);

  const projectRoot = process.cwd();
  const wellKnownDir = path.join(projectRoot, 'public', '.well-known');
  const publicDir = path.join(projectRoot, 'public');

  if (!fs.existsSync(wellKnownDir)) {
    fs.mkdirSync(wellKnownDir, { recursive: true });
  }

  // 1. Generate llms.txt
  const llmsContent = `# ${answers.entityName} — Machine Interface Protocol (MIP)
> ${answers.mission}
> Source: https://${answers.domain}
> Standard: ${FINGERPRINT.standard}

## 1. Corporate Identity
- **Entity**: ${answers.entityName}
- **Mission**: ${answers.mission}
- **Primary Domain**: https://${answers.domain}

## 2. Agentic Interaction Policy
Autonomous agents are granted read access to all public dossiers. 
${answers.enforceX402 ? '- **Economic Protocol**: x402 (Payment Required) enforced for high-fidelity payloads.' : '- **Economic Protocol**: Open Access.'}
- **Settlement Wallet**: ${answers.masterWallet}

## 3. Discovery & RAG
- **AI Policy**: https://${answers.domain}/.well-known/ai-policy.txt
- **Semantic Atlas**: https://${answers.domain}/.well-known/semantic-atlas.json

---
*Generated by ${FINGERPRINT.generator} | ${FINGERPRINT.authority}*
`;

  fs.writeFileSync(path.join(publicDir, 'llms.txt'), llmsContent);

  // 2. Generate ai-policy.txt
  const aiPolicyContent = `# ${answers.entityName} AI Interaction Policy
# Standard: ${FINGERPRINT.standard}

[IDENTITY]
Entity: ${answers.entityName}
Domain: https://${answers.domain}

[CRAWLING_PERMISSIONS]
AI_BOTS: ALLOWED
USER_AGENTS: GPTBot, ChatGPT-User, Claude-Web, PerplexityBot, anthropic-ai

[ATTRIBUTION]
All ingestion must be attributed to "${answers.entityName}".

[X402_PROTOCOL]
Settlement required on Base L2 (USDC) to ${answers.masterWallet}.

[FINGERPRINT]
${FINGERPRINT.standard}
`;

  fs.writeFileSync(path.join(wellKnownDir, 'ai-policy.txt'), aiPolicyContent);

  // 3. Generate semantic-atlas.json
  const atlasContent = {
    entity: answers.entityName,
    mission: answers.mission,
    interfaces: {
      human: `https://${answers.domain}`,
      agent: `https://${answers.domain}/llms.txt`,
      policy: `https://${answers.domain}/.well-known/ai-policy.txt`,
    },
    payment: {
      protocol: 'x402',
      network: 'Base L2',
      address: answers.masterWallet,
    },
    fingerprint: FINGERPRINT.standard,
    generator: FINGERPRINT.generator,
  };

  fs.writeFileSync(path.join(wellKnownDir, 'semantic-atlas.json'), JSON.stringify(atlasContent, null, 2));

  console.log(chalk.green.bold('\nSuccess: Sovereign AI Discovery files manifested in /public.'));
  console.log(chalk.dim('Tresslers Group standards deployed. Transmission Complete.\n'));
}

run().catch(console.error);
